### PR TITLE
Propose change of address to Contract Instance Object.

### PR DESCRIPTION
**Pull request by VoR0220**
Addresses should be an array and be updated for every time there is a deployment I think. Or at the very least leave the option open for such a package if that is desired.

### CODE REVIEW

**Comment by tcoulter** [comment]
Aren't past addresses stored forever in old lockfiles? Each time you publish a new package, if you've redployed, the new address will exist in the lockfile.

**Comment by VoR0220** [comment]
I suppose that could be the case, but even so, say I have a factory and deploy numerous instances of said contract from a certain contract with only an enum changed that effects the functionality of the entire contract. In this instance we would want those addresses recorded, would we not?

**Comment by tcoulter** [comment]
Good point. Perhaps `address` should be `addresses`?

**Comment by VoR0220** [comment]
or `address(es)`

**Comment by tcoulter** [comment]
I don't like ambiguity -- this is mostly a machine readable doc, so an `addresses` array with a single entry is perfectly fine. It's extra work if it can be a string or an array. If this were the manifest I might argue differently; but this is for the lockfile so we might as well constrain the possibilities.

**Comment by tcoulter** [comment]
Sorry, I think my response sounds strong via text. Not trying to just shut you down.

**Comment by pipermerriam** [comment]
This case is covered.  The `contracts` key would look something like this.

```javascript
{
  ...
  'contracts': {
    'MKRToken': {
      'contract_name': 'StandardToken',
      ...,
    },
        'DAIToken': {
      'contract_name': 'StandardToken',
      ...,
    },
  },
}
```

**Comment by VoR0220** [comment]
@pipermerriam that sounds like more to parse and that's the problem. That'll bloat the file.

**Comment by pipermerriam** [comment]
Was there resolution on this?  I think we decided to stick with the current spec.  If that is the case can we close this?

**Comment by VoR0220** [comment]
close for now yes. I think we definitely should revisit this at a later time.

**Pull request closed without merging**
